### ISSUE TITLE
femto_mac_address.yaml may overwrite General settings in config.yaml

### ISSUE THREAD

**Issue by pdxlocations** [femtofox/femtofox#355]
In my testing, femto_mac_address.yaml may cause defaults to be used for the General setting MaxNodes, and possibly others in config.yaml

Setting config.yaml to (note the db size):
```
General:
  MaxNodes: 500
  MaxMessageQueue: 100
  ConfigDirectory: /etc/meshtasticd/config.d/
#  MACAddress: AA:BB:CC:DD:EE:FF
#  MACAddressSource: eth0
```

and config.d/femto_mac_address.yaml to:
```
General:
  MACAddressSource: eth0
```

results in a max nodedb of the default 200.
```
Feb 18 22:55:30 femtofox meshtasticd[2519]: INFO  | 06:55:29 1800 [Router] Node database full with 200 nodes and 4294967295 bytes free. Erasing oldest entry
```
Removing the later file increases the db over 200.
```
Feb 18 23:18:51 femtofox meshtasticd[350]: INFO  | 07:18:43 763 [Router] Adding node to database with 212 nodes and 4294967295 bytes free!
```
